[project]
name = 'Decentralized-Playground-Safety-Inspection'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.equipment-registry]
path = 'contracts/equipment-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.incident-reporter]
path = 'contracts/incident-reporter.clar'
clarity_version = 2
epoch = 2.5

[contracts.inspection-scheduler]
path = 'contracts/inspection-scheduler.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-tracker]
path = 'contracts/maintenance-tracker.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
